theme = "gruvbox"

[editor]
bufferline = "multiple"
completion-trigger-len = 1
idle-timeout = 5
preview-completion-insert = false
line-number = "relative"
auto-pairs = false
text-width = 180


[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
max-indent-retain = 80
max-wrap = 25

# [editor.indent-guides]
# render = true
