[[language]]
name = "python"
auto-format = true
[language.formatter]
command = "black"
args = [
  "-",
  "--quiet",
  "--line-length=100"
]


[[language]]
name = "latex"
language-servers = ["texlab"]

[language-server.ltex]
command = "ltex-ls"
[language-server.texlab.config.texlab.build]
onSave = true


[language-server]
ols = { command = "ols", args = []}


[[language]]
name = "odin"
#auto-format = false
scope = "scope.odin" # "source.odin"
file-types = ["odin"]
roots = ["ols.json"]
language-servers = [ "ols" ]
comment-token = "//"
indent = { tab-width = 2, unit = " " }
injection-regex = "odin"
formatter = { command = "odinfmt", args = [ "-stdin", "true" ] }

[[grammar]]
name = "odin"
#source = { git = "https://github.com/ap29600/tree-sitter-odin", rev = "b219207e49ffca2952529d33e94ed63b1b75c4f1" }
source = { git = "https://github.com/amaanq/tree-sitter-odin" }

[language-server.clangd]
args = [ "--query-driver=/nix/store/7zrbj0f8pwvard552qm736c0w2v3s8s9-gcc-arm-embedded-12.3.rel1/bin/arm-none-eabi-gcc" ]
